App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import ( 
                    index, signup, tasks, signout, signin, create_tasks,
                    tasks_detail, complete_tasks, delete_tasks, tasks_completed,
                    profile, edit_profile, change_password, delete_user, alert_message,
                    list_of_contact, list_of_contact_detail, create_list_of_contact, 
                    contact, delete_contact
                    )

urlpatterns = [
    path('', index, name='index'),   
    path('signup/', signup, name='signup'),                        
    path('tasks/', tasks, name='tasks'),                             
    path('tasks_completed/', tasks_completed, name='tasks_completed'),                             
    path('tasks/create/', create_tasks, name='create_tasks'),        
    path('tasks/<int:task_id>/', tasks_detail, name='tasks_detail'),        
    path('tasks/<int:task_id>/complete', complete_tasks, name='complete_tasks'),        
    path('tasks/<int:task_id>/delete', delete_tasks, name='delete_tasks'),        
    path('profile/', profile, name='profile'),        
    path('profile/edit_profile/', edit_profile, name='edit_profile'),        
    path('profile/edit_profile/delete_user/', delete_user, name='delete_user'),        
    path('profile/edit_profile/delete_user/alert_message/', alert_message, name='alert_message'),        
    path('list_of_contact/', list_of_contact, name='list_of_contact'), 
    path('list_of_contact/create/', create_list_of_contact, name='create_list_of_contact'),       
    path('list_of_contact/<int:contact_id>/', contact, name='contact'),        
    path('list_of_contact/<int:contact_id>/detail', list_of_contact_detail, name='list_of_contact_detail'),        
    path('list_of_contact/<int:contact_id>/delete_contact', delete_contact, name='delete_contact'),        
    path('change_password/', change_password, name='change_password'),        
    path('logout/', signout, name='logout'),                         
    path('signin/', signin, name='signin'),   
                           
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

App/models.py
from django.db import models 
from django.contrib.auth.models import User 

class Profile_User(models.Model):
    user = models.OneToOneField( User, on_delete = models.CASCADE)
    image = models.ImageField( default = 'user.png')
    
    def __str__(self):
        return f'Perfil de {self.user.username}'        

class Tasks(models.Model):                                      
    title = models.CharField( max_length = 100 )                 
    description = models.TextField( blank = True )              
    created = models.DateTimeField( auto_now_add = True )       
    datecompleted = models.DateTimeField( null = True, blank = True ) 
    important = models.BooleanField( default = True )             
    user = models.ForeignKey( User, on_delete = models.CASCADE )  

    def __str__(self):
        return self.title + ' - by ' + self.user.username        

class List_of_contact(models.Model):
    name = models.CharField( max_length = 100 )
    last_name = models.CharField( max_length = 100)
    phone = models.IntegerField()
    adress = models.CharField( max_length = 100, blank = True )
    email = models.CharField( max_length= 100, blank = True )
    user = models.ForeignKey( User, on_delete = models.CASCADE )
    image_contact = models.ImageField( default = 'user.png')
    
    def __str__(self):
        return self.last_name + ', '+ self.name +' - by ' + self.user.username

App/templates/App/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <title>To-Do-App</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navBar">
            <a href="/" class="navBranding">
                <img src="{% static 'assets/to-do-App-logo.ico' %}" href="/" alt="logo" class="logo">
            </a>
            <ul class="navMenu">
                <li class="navItem">
                    <a class="navLink actives" href="/">Home</a>
                </li>

                {% if user.is_authenticated %}
                    <li class="navItem">
                        <a class="navLink" href="{% url 'list_of_contact' %}">Agenda</a>
                    </li>
                    <li class="navItem">
                        <a class="navLink" href="{% url 'tasks' %}">Tareas</a>
                    </li>
                    <li class="navItem d-inline-block">
                        <li class="navItem">
                            <a class="navLink" href="{% url 'logout' %}">Salir</a>
                        </li>
                        <a class="navLink" href="{% url 'profile' %}">Hola {{user.username}}!        
                            <span>
                                <img src="{{ user.profile_user.image.url }}" style="width: 35px; border-radius: 50%; margin-left: 5px;">
                            </span>  
                        </a>
                    </li>
                    {% else %}
                    <li class="navItem">
                        <a class="navLink" href="{% url 'signup' %}">Registrate</a>
                    </li>
                    <li class="navItem">
                        <a class="navLink" href="{% url 'signin' %}">Ingresar</a>
                    </li>
                {% endif%}
            </ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </header>
    {% block content %}

    {% endblock %}
    <script src="{% static 'js/navBar.js' %}" type="">></script>
    <div>
        <a href="mailto:baranda.gustavo@gmail.com" target="_blank">
            <p class="copyright">
                &copy; Copyright Proyecto final Python Coderhouse - 2022<br>Gustavo Baranda FRONT-END DEVELOPER
            </p>
        </a>
    </div> 
</body>

</html>

App/templates/App/change_password.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main h-100">
    <div class="row">
        <section class="col-md-4 offset-md-4">
            <form  method='POST' class="card card-body">
                {% csrf_token %}
                <h1 class="text-center">Cambio de Contraseña</h1>
                <p style="color:red; font-weight:bold">{{ error }}</p>              
                <div class="mb-3">
                    <label for="password1" class="text-center">Contraseña</label>
                    <input type="password" name="password1" class="form-control bg-light border-1 small" id="password1"
                        placeholder="Ingrese su nueva Contraseña..." required/>
                </div>
                <div class="mb-3">
                    <label for="password2" class="text-center">Comfirme su contraseña</label>
                    <input type="password" name="password2" class="form-control bg-light border-1 small" id="password2"
                        placeholder="Comfirme su nueva contraseña..." required/>
                </div>
                <button class="btn btn-primary">Cambiar contraseña</button>
            </form>
        </section>
    </div>
</main>
{% endblock %}

App/templates/App/contact.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-4 offset-md-4"> 
            <div class="card card-body">
                <h1 class="text-center pb-2">Contacto</h1> 
                <img src="{{ contact.image_contact.url }}" style="width: 100px; margin: 0 auto; border-radius: 50%;" class="mt-2 mb-3">
                <div class="card card-body">  
                    <h4>Nombre: {{contact.name}}</h4>
                    <h4>Apellido: {{contact.last_name}}</h4>
                    <h4>Telefono: {{contact.phone}}</h4>
                    <h4>Correo: {{contact.email}}</h4>   
                    <h4>Domicilio: {{ contact.adress }} </h4>
                    <a href="{% url 'list_of_contact_detail' contact.id %}" class="btn btn-success mt-2">Modificar Contacto</a>
                    <form action="{% url 'delete_contact' contact.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-danger w-100 mt-2">Eleminar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main> 
{% endblock %}

App/templates/App/create_list_of_contact.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <form action="/list_of_contact/create/" method="POST" class="card card-body">
                <h1 class="text-center">Nueva Tarea</h1>
                <p>{{error}}</p>
                {% csrf_token %}
                {{form}}
                <!-- <div class="mb-3">
                    <label for="id_name" class="text-center">Nombre:</label>
                    <input type="text" name="name" class="form-control" id="id_name"
                        placeholder="Escriba una tarea">
                </div>
                <div class="mb-3">
                    <label for="id_last_name" class="text-center">Apellido:</label>
                    <input type="text" name="description" class="form-control" id="id_description"
                        placeholder="Escriba una tarea">
                </div>
                <div class="mb-3">
                    <label for="id_phone" class="text-center">Telefono:</label>
                    <input type="number" name="phone" class="form-control" id="id_phone" 
                        placeholder="Escriba una tarea">
                </div>
                <div class="mb-3">
                    <label for="id_email" class="text-center">Email:</label>
                    <input type="text" name="email" class="form-control" id="id_email" 
                        placeholder="Escriba una tarea">
                </div> -->
                <button class="btn btn-primary">Guardar</button>
            </form>
         </div>
    </div>
</main>   
{% endblock %}

App/templates/App/create_tasks.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <form action="/tasks/create/" method="POST" class="card card-body">
                <h1 class="text-center">Nueva Tarea</h1>
                <p>{{error}}</p>
                {% csrf_token %}
                <a class="btn btn-primary mb-2" href="{% url 'tasks' %}">Tareas Pendientes</a>
                <a class="btn btn-primary mb-2" href="{% url 'tasks_completed' %}">Tareas Realizadas</a>
                <a class="btn btn-primary mb-2" href="{% url 'create_tasks' %}">Nueva Tarea</a>
                <div class="mb-3">
                    <label for="id_title" class="text-center">Titulo:</label>
                    <input type="text" name="title" class="form-control" id="id_title"
                        placeholder="Escriba una tarea">
                </div>
                <div class="mb-3">
                    <label for="id_description" class="text-center">Descripcion:</label>
                    <textarea type="text" name="description" cols="40" rows="10" class="form-control" id="id_description"
                        placeholder="Escriba una tarea"></textarea>
                </div>
                <div class="mb-3">
                    <label for="id_important" class="text-center">Importante:</label>
                    <input type="checkbox" name="important" class="form-check-input text-center" id="id_important" checked
                        placeholder="Escriba una tarea">
                </div>
                <button class="btn btn-primary">Guardar</button>
            </form>
         </div>
    </div>
</main>   
{% endblock %}

App/templates/App/edit_profile.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-4 offset-md-4"> 
            <form method="POST" class="card card-body" enctype="multipart/form-data">
                {% csrf_token %}
                <h1 class="text-center pb-2">Modificar Perfil</h1> 
                <div class="mb-3">
                    <label for="username" class="text-center">Usuario</label>
                    {{ u_form.username }}
                </div>
                <div class="mb-3">
                    <label for="first_name" class="text-center">Nombre</label>
                    {{ u_form.first_name }}
                </div>
                <div class="mb-3">
                    <label for="last_name" class="text-center">Apellido</label>
                    {{ u_form.last_name }}
                </div>
                <div class="mb-3">
                    <label for="email" class="text-center">Correo</label>
                    {{ u_form.email}}
                </div>
                <div class="mb-3">
                    <label for="image" class="text-center">Imagen de Perfil</label>
                    {{ p_form }}
                </div> 
                <button class="btn btn-primary mt-2">Modificar Perfil</button>
            </form>
           
        </div>
    </div>
</main> 
{% endblock %}

App/templates/App/index.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container-xxl main">
    <section class="card card-body">
        <h1 class="display-1 text-center">Home</h1>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis quos dignissimos dolore dolorum aliquam ut
            placeat adipisci ea consequatur aspernatur, magni officiis, dicta in, possimus facilis nihil. Voluptatem,
            cum explicabo.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis quos dignissimos dolore
            dolorum aliquam ut placeat adipisci ea consequatur aspernatur, magni officiis, dicta in, possimus facilis
            nihil. Voluptatem, cum explicabo.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis quos
            dignissimos dolore dolorum aliquam ut placeat adipisci ea consequatur aspernatur, magni officiis, dicta in,
            possimus facilis nihil. Voluptatem, cum explicabo.Lorem ipsum dolor, sit amet consectetur adipisicing elit.
            Corporis quos dignissimos dolore dolorum aliquam ut placeat adipisci ea consequatur aspernatur, magni
            officiis, dicta in, possimus facilis nihil. Voluptatem, cum explicabo.Lorem ipsum dolor, sit amet
            consectetur adipisicing elit. Corporis quos dignissimos dolore dolorum aliquam ut placeat adipisci ea
            consequatur aspernatur, magni officiis, dicta in, possimus facilis nihil. Voluptatem, cum explicabo.Lorem
            ipsum dolor, sit amet consectetur adipisicing elit. Corporis quos dignissimos dolore dolorum aliquam ut
            placeat adipisci ea consequatur aspernatur, magni officiis, dicta in, possimus facilis nihil. Voluptatem,
            cum explicabo.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis quos dignissimos dolore
            dolorum aliquam ut placeat adipisci ea consequatur aspernatur, magni officiis, dicta in, possimus facilis
            nihil. Voluptatem, cum explicabo.Lorem ipsum dolor, sit amet consectetur adipisicing elit. Corporis quos
            dignissimos dolore dolorum aliquam ut placeat adipisci ea consequatur aspernatur, magni officiis, dicta in,
            possimus facilis nihil. Voluptatem, cum explicabo.</p>
        <div class="text-center">
            <a class="btn btn-secondary" href="{% url 'signup' %}">Registrate</a>
            <a class="btn btn-dark" href="{% url 'signin' %}">Ingresar</a>
        </div>

    </section>
</main>
{% endblock %}

App/templates/App/list_of_contact.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <section class="col-md-4 offset-md-4">
           <div class="card card-body">
            <table class="table caption-top">
                <h1 class="text-center">Contactos</h1>
                <form  class="d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search pt-3 pb-3}" method="POST">
                    {% csrf_token %}
                    <div class="input-group p-3">
                        <input type="text" class="form-control bg-light border-1 small " placeholder="Buscar..." name="buscar" value="{{ request.POST.buscar }}">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit"> Buscar</button>
                        </div>
                    </div>
                  </form>
                <thead>
                  <tr>
                    <th class="text-center" scope="col">Imagen</th>
                    <th class="text-center" scope="col">contacto</th>
                    <th class="text-center" scope="col">Accion</th>
                </tr>
                </thead>
                <tbody>
                {% for c in contact %}
                    <tr class="">
                        <th class="text-center pt-0" scope="row"><img src="{{ c.image_contact.url }}" style="width: 50px;"></th>
                        <td class="text-center pt-3">{{c.last_name}}, {{c.name}}</td>
                        <td class="text-center"><a class="btn btn-primary" href="{% url 'contact' c.id %}">Ver</a></td>
                    </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>            
        </section>
    </div>
</main>
{% endblock %}

App/templates/App/list_of_contact_detail.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-4 offset-md-4"> 
            <div class="card card-body">
                <form method="POST">
                    {% csrf_token %}
                    <h1 class="text-center">Detalles de la Tarea</h1>
                    {{error}}
                    {{form.as_p}}
                    <button class="btn btn-primary w-100">Actualizar</button>
                </form>
             
            </div>
        </div>
    </div>
</main> 
{% endblock %}

App/templates/App/profile.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-6 offset-md-3"> 
            <div class="card card-body">
                <h1 class="text-center pb-2">Perfil de {{user.username}}</h1> 
                <img src="{{ profile.profile_user.image.url }}" style="width: 100px; margin: 0 auto; border-radius: 50%;">  
                <h3>Usuario: {{profile.username}}</h3>
                <h3>Nombre: {{profile.first_name}}</h3>
                <h3>Apellido: {{profile.last_name}}</h3>
                <h3>Correo: {{profile.email}}</h3>   
                <a href="{% url 'edit_profile' %}" class="btn btn-success mt-2">Modificar Perfil</a>
                <a href="{% url 'change_password' %}" class="btn btn-warning mt-2">Modificar contraseña</a>
                <a href="{% url 'alert_message' %}" class="btn btn-danger mt-2">Eliminar Cuenta</a>
            </div>
        </div>
    </div>
</main> 
{% endblock %}

App/templates/App/signin.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <section class="col-md-4 offset-md-4">
            <form action="/signin/" method='POST' class="card card-body">
                {% csrf_token %}
                <h1 class="text-center">Iniciar sesión</h1>
                <p>{{error}}</p>                
                <div class="mb-3">
                    <label for="username" class="text-center">Usuario</label>
                    <input type="text" name="username" class="form-control" id="username"
                        placeholder="Escriba su usuario" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="text-center">Contraseña</label>
                    <input type="password" name="password" class="form-control" id="password"
                        placeholder="Escriba su contraseña" required>
                </div>
                <button class="btn btn-primary">Iniciar Sesión</button>
            </form>
        </section>
    </div>
</main>
{% endblock %}

App/templates/App/signup.html
{% extends 'App/base.html' %} {% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form method="POST" class="card card-body">
                <h1 class="text-center">Creá tu cuenta</h1>
                <p>{{error}}
                </p> {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="text-center">Usuario</label>
                    <input type="text" name="username" class="form-control bg-light border-1 small" id="username"
                        placeholder="Usuario..." required/>
                </div>
                <div class="mb-3">
                    <label for="first_name" class="text-center">Nombre</label>
                    <input type="text" name="first_name" class="form-control bg-light border-1 small" id="first_name"
                        placeholder="Nombre..." required/>
                </div>
                <div class="mb-3">
                    <label for="last_name" class="text-center">Apellido</label>
                    <input type="text" name="last_name" class="form-control bg-light border-1 small" id="last_name"
                        placeholder="Apellido..." required/>
                </div>
                <div class="mb-3">
                    <label for="email" class="text-center">Correo electronico</label>
                    <input type="email" name="email" class="form-control bg-light border-1 small" id="email"
                        placeholder="Ingrese su Correo..." required/>
                </div>
                <div class="mb-3">
                    <label for="password1" class="text-center">Contraseña</label>
                    <input type="password" name="password1" class="form-control bg-light border-1 small" id="password1"
                        placeholder="Contraseña..." required/>
                </div>
                <div class="mb-3">
                    <label for="password2" class="text-center">Comfirme su contraseña</label>
                    <input type="password" name="password2" class="form-control bg-light border-1 small" id="password2"
                        placeholder="Comfirme su contraseña..." required/>
                </div>
                <button class="btn btn-primary">Registrate</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

App/templates/App/tasks.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
  <div class="row">
    <div class="col-md-6 offset-md-3"> 
      <div class="card card-body">
        {% if count == 0 and tasks_completed %}
          <h1 class="text-center display-4">Tareas Pendientes</h1>
          <h5>Aun no tienes tareas registradas, puedes registrar una en Nueva Tarea!</h5>
          <a class="btn btn-primary mb-2" href="{% url 'tasks_completed' %}">Tareas Realizadas</a>
          <a class="btn btn-primary mb-2" href="{% url 'create_tasks' %}">Nueva Tarea</a>
        {% elif search_input %}       
          <h1 class="text-center display-4">Resultado de la Busqueda</h1>
          <h5>se registra{{ count|pluralize:"ron" }} <i>{{count}}</i> tarea{{ count|pluralize:"s" }} sin completar!</h5>
          <a class="btn btn-primary mb-2" href="{% url 'tasks' %}">Tareas Pendientes</a>
          <a class="btn btn-primary mb-2" href="{% url 'tasks_completed' %}">Tareas Realizadas</a>
          <a class="btn btn-primary mb-2" href="{% url 'create_tasks' %}">Nueva Tarea</a>
        {% elif tasks_completed %}
          <h1 class="text-center display-4">Tareas Pendientes</h1>
          <h5>Tienes <i>{{count}}</i> tarea{{ count|pluralize:"s" }} sin completar!</h5>
          <a class="btn btn-primary mb-2" href="{% url 'tasks_completed' %}">Tareas Realizadas</a>
          <a class="btn btn-primary mb-2" href="{% url 'create_tasks' %}">Nueva Tarea</a>
        {% elif count == 0 and not tasks_completed %}
          <h1 class="text-center display-4">Tareas Realizadas</h1>
          <h5>Aun no tienes tareas Realizadas!</h5>
          <a class="btn btn-primary mb-2" href="{% url 'tasks' %}">Tareas Pendientes</a>
          <a class="btn btn-primary mb-2" href="{% url 'create_tasks' %}">Nueva Tarea</a>
        {% else %}
          <h1 class="text-center display-4">Tareas Realizadas</h1>
          <h5>Tienes <i>{{count}}</i> tarea{{ count|pluralize:"s" }} completadas!</h5>
          <a class="btn btn-primary mb-2" href="{% url 'tasks' %}">Tareas Pendientes</a>
          <a class="btn btn-primary mb-2" href="{% url 'create_tasks' %}">Nueva Tarea</a>
        {% endif %}
        <form  class="d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search pt-3 pb-3" method="POST">
          {% csrf_token %}
          <div class="input-group">
              <input type="text" class="form-control bg-light border-1 small" placeholder="Buscar..." name="buscar" value="{{ request.POST.buscar }}">
              <div class="input-group-append">
                  <button class="btn btn-primary" type="submit"> Buscar</button>
              </div>
          </div>
        </form>
        <ul class="list-group">
          {% for task in tasks %}
          <a class="list-group-item mb-2" href="{% url 'tasks_detail' task.id %}">
            <header class="d-flex justify-content-between">
              {% if task.important %}
              <h5 class="fw-bold text-danger">{{task.title}}</h5>
              {% else %} 
              <h5 class="text-warning">{{task.title}}</h5>   
              {% endif %}
              <p class="text-primary fw-bold">by- {{task.user.username}}</p>
            </header>  
            <p class="text-secondary">{{task.description}}</p>
            <p class="text-end fs-6 text-muted">Creado: {{task.created | date:'j-M-Y h:m'}}</p>
            {% if not tasks_completed %}
            <p class="text-end fs-6 text-muted">Terminada: {{task.datecompleted | date:'j-M-Y h:m'}}</p>
            {% endif %}
          </a>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock %}

App/templates/App/tasks_detail.html
{% extends 'App/base.html' %}

{% block content %}
<main class="container main">
    <div class="row">
        <div class="col-md-4 offset-md-4"> 
            <div class="card card-body">
                <form method="POST">
                    {% csrf_token %}
                    <h1 class="text-center">Detalles de la Tarea</h1>
                    {{error}}
                    {{form.as_p}}
                    <button class="btn btn-primary w-100">Actualizar</button>
                </form>
                <form action="{% url 'complete_tasks' tasks.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-secondary w-100 mt-2">Realizada</button>
                </form>
                <form action="{% url 'delete_tasks' tasks.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger w-100 mt-2">Eleminar</button>
                </form>
            </div>
        </div>
    </div>
</main> 
{% endblock %}